name: selenium_tutorial
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pytest with Chrome

        run: |
          mkdir -p reports
          python download_reel.py
          chmod 777  /home/runner/work/insta_to_youtube/insta_to_youtube/reports/

      - name: Set output
        if: always()
        id: results
        run: echo "artifactPath=reports/" >> $GITHUB_OUTPUT

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-try
          path: reports